name: run-tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  run-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: run pytest
        run: uv run pytest
